### ISSUE TITLE
const_cast

### ISSUE THREAD

**Issue by aepkolol** [xyz-1/Overlay#1]
In my DLC ESP drawing additions, I'm not sure if I should use const_cast or not. 

`DrawString(const_cast<char*>(ActorArray.at(i).name.c_str()), ScreenPoint.x, ScreenPoint.y, 230, 230, 250, pFontSmall);`

vs

`DrawString((char*)ActorArray.at(i).name.c_str(), ScreenPoint.x, ScreenPoint.y, 230, 230, 250, pFontSmall);`

Just making sure you're aware of that if I screwed something up.

**Comment by xyz-1** [comment]
Thanks, can't tell if this would have any impact, but i changed it to make it consistent.
